### ISSUE TITLE
add branch creator gha

### ISSUE THREAD

**Issue by kfarkasHU** [wraithlight/wraithlight-mono#640]
```yaml

  create-release-branch:
    needs: [Build]
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y%m%d')"
      - name: Publish release branch
        uses: peterjgrainger/action-create-branch@v2.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: 'refs/heads/release/${{ steps.date.outputs.date }}_${{ github.event.inputs.version }}'
          sha: '${{ github.event.pull_request.head.sha }}'

```
